### ISSUE TITLE
关于conv1d，和local_conv1d，softmax层以及胶囊中池化层的问题

### ISSUE THREAD

**Issue by GongYangYu** [bojone/Capsule#2]
您好，我想问下您使用了conv1d，和local_conv1d，但是这种操作还算是矩阵乘法么？我不太清楚conv1d的机制，网上好像也都讲的不太清楚。能详细说明下么，这个操作能代替W_ij*u_i？
还有，我不太理解您自己定义的softmax，为什么要减去一个最大值？再者看原文，softmax中求和应该是对j累加，也就是说对caps_num累加，看您的程序好像是对i累加了。
最后，Hiton貌似是不希望增加池化层的，但看你的程序好像加了个cnn = AveragePooling2D((2,2))(cnn)，是否不太合适？
最后谢谢您分享的代码，它在速度上的提升令人振奋！

**Comment by GongYangYu** [comment]
另外，我希望和您进一步交流胶囊网络，不知可否留下联系方式，我的qq是983194327。

**Comment by bojone** [comment]
1、conv1d是一维卷积，local_conv1d是不共享权重的一维卷积，它们都是矩阵乘法，你了解一维卷积后就明白了，如果你有tensorflow下conv1d的使用经验，那应该是容易懂的，如果没有，我也帮不了你了。
2、softmax先减去最大值，然后再算exp，这是标准做法，所有框架都一样，最后我通过softmax(b, 1)指定了求和维度；
3、hinton说干啥我们就要干啥么？原因参考http://kexue.fm/archives/4819/#%E6%B1%A0%E5%8C%96%E5%A5%BD%E4%B8%8D%E5%A5%BD%EF%BC%9F

**Comment by GongYangYu** [comment]
Thank you,麻烦再问下conv1，local_conv1d对应tensorflow中的哪些呢？都是tf.nn.conv1d么？

**Comment by bojone** [comment]
conv1d对应tf.nn. conv1d
local_conv1d并没有对应，是keras自己写的，思想跟batch_dot一致，你可以直接看keras的tf backend的源码

**Comment by GongYangYu** [comment]
哦哦，行，万分感谢！
