### ISSUE TITLE
squash function

### ISSUE THREAD

**Issue by llwc** [bojone/Capsule#3]
From the paper "Dynamic Routing Between Capsules", I think the squash function should be 
scale = K.sqrt(s_squared_norm)/ (K.sqrt(s_squared_norm) + s_squared_norm) 
rather than the function written in you code
scale = K.sqrt(s_squared_norm)/ (0.5 + s_squared_norm)
When I change it to function in the paper, the accuracy get improved to 0.936. Could you try it?

**Comment by llwc** [comment]
But I don't know why this function is better than the squash function in the paper. can you explain a little bit?

**Comment by bojone** [comment]
you can see the derivation from my article https://kexue.fm/archives/5112

My new dynamic routing results from the soft version of k-means with the metric eq.11.  And the hinton's can not be corresponding to any cluster processing. So in theory mine is better.

In practices, my dynamic routing keep the norm of center vector to 1, only squash it after finishing routing, which guarantees the resolution of all centers during clustering. that will guarantees the feature representation ability of capsule.

**Comment by llwc** [comment]
Yes, I try your new code, it did improve the performance and also very reasonable.

**Comment by llwc** [comment]
And I also remove the squash function in the experiment, and get the same accuracy, could mean that squash function is not necessary? The point is that normalization is enough in each iteration?

**Comment by bojone** [comment]
actually, squash function is not necessary during dynamic routing. but we could squash the final output capsule of routing.

in my opinion, squash is a good operating to get the reasonable capsule, but it will lead to training difficulty(vanishing gradient like sigmoid activation).

**Comment by llwc** [comment]
I mean I remove the squash in the final step, still get the same result.

**Comment by bojone** [comment]
yes, because squash is a monotonically increasing function of norm, it will not add or loss any information. squash is necessary only when you a probability explain of capsule norm.

**Comment by llwc** [comment]
Yeah, you are right, I got it.
