### ISSUE TITLE
capsule 类中的b没有更新

### ISSUE THREAD

**Issue by tw19941212** [bojone/Capsule#8]
b = K.batch_dot(o, u_hat_vecs, [2, 3])
应该是
b += K.batch_dot(o, u_hat_vecs, [2, 3])

**Comment by tw19941212** [comment]
噢我看了博客,那请问你有没有做相关比较最终俩者的性能差异呢

**Comment by bojone** [comment]
纠正一个说法，b = K.batch_dot(o, u_hat_vecs, [2, 3])就是一种更新，为什么说它没有更新？

至少在我的实验中，原版动态路由，效果远没有我修改后的版本好（我修改了好几处，并不只是这一处）
